name: Rômulo Jales
description: sobre coisas aleatórias
meta_description: "opiniões sobre coisas aleatórias "

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: ''
domain_name: 'http://romulojales.com'
google_analytics: 'UA-38627485-1'
disqus_shortname: 'romulojales'
# Details for the RSS feed generator
url:            'http://romulojales.com'
author:         'Rômulo Jales'
authorTwitter:  'romulojales'
authorEmail:    'romulo@romulojales.com'

permalink:       :title/

locale: "pt-br"

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

gems:
  - jekyll-sitemap